name: "learn-aws-wordpress-ec2"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}

jobs:
  terraform:
    name: "learn-aws-wordpress-ec2"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize, Format, Validate and Plan Terraform
        run: |
          terraform init
          terraform fmt
          terraform validate
          terraform plan

      - name: Apply Terraform configuration
        run: |
          terraform apply -var-file="terraform.tfvars.json" -auto-approve -input=false

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/davidawcloudsecurity/learn-terraform-aws-wordpress-ec2.git          
          git fetch origin destroy/main
          git checkout destroy/main
          git merge origin/destroy/main
          mv terraform.tfstate state         
          git add state
          git commit -m "random"
          git push origin destroy/main
      - name: Terraform Destroy on Failure
        if: failure()
        run: |
          terraform destroy -var-file=terraform.tfvars.json -auto-approve -input=false          
