name: "learn-aws-wordpress-ec2-destroy"

on:
  push:
    branches: [ "destroy/main" ]
  pull_request:
    branches: [ "destroy/main" ]

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}

jobs:
  destroy:
    name: "Destroy AWS Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          
      - name: Initialize Terraform
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Destroy
        run: terraform destroy -target aws_vpc.main -target aws_instance.web-auto-approve -input=false
