name: "learn-aws-wordpress-ec2"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}

jobs:
  terraform:
    name: "learn-aws-wordpress-ec2"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize and Format Terraform
        run: |
          terraform init
          terraform fmt

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Apply Terraform configuration
        run: |
          terraform apply -var-file="terraform.tfvars.json" -auto-approve -input=false || export BUILD_FAILED=true
          if [ "$BUILD_FAILED" == "true" ]; then
            echo "Build failed, sending alert and triggering destroy"
            terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
            exit 1
          fi

      - name: Terraform State
        run: |
          terraform state list
          cat terraform.tfstate
          ls -lah
          pwd
          terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
