name: "learn-aws-wordpress-ec2-destroy"

on:
  push:
    branches: [ "destroy/main" ]
  pull_request:
    branches: [ "destroy/main" ]

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}

jobs:
  destroy:
    name: "Destroy AWS Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          
      - name: Initialize, validate, format Terraform
        run: |
          ls -lah
          pwd
          ls -lah state
          mv state/terraform.tfstate ./terraform.tfstate
          ls -lah
          echo "Terraform init"
          echo ""
          terraform init
          terraform validate
          terraform fmt
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform State
        run: terraform state list        
        
      - name: Terraform Destroy Targeted Resources
        run: |
          terraform destroy -auto-approve

      - name: Clean OS
        run: |
          pwd
          ls -lah
          cd ..
          pwd
          ls -lah
          cd ..
          pwd
          ls -lah
#          rm -rf learn-terraform-aws-wordpress-ec2
          ls -lah
          
